### ISSUE TITLE
Issue with salem when running workflow.init_glacier_directories

### ISSUE THREAD

**Issue by RPellitero** [OGGM/oggm#1231]
Dear fmaussion, 
Thanks a lot for this nice model. I am trying to run it but I keep on getting error messages related to the salem package. It is installed in my oggm_env, I will try to explain: 

When I try:

`gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=3, prepro_border=80)`

I get the following error message: 

_crs = salem.check_crs(rgi_entity.crs)

NameError: name 'salem' is not defined_

This happens in **workflow.py** because salem is not imported, despite it is installed within the environment. Furthermore, I have tried to run the tests within salem package, and all yield the same error: 

'ImportError: cannot import name '_MultiFileCloser' from 'xarray.backends.api' (/home/mon/miniconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/api.py)'

I am working in Ubuntu20.04 within a Virtual Box. 
Thanks a lot for your help.

**Comment by fmaussion** [comment]
What happens when you try to import `salem` from the command line?

**Comment by RPellitero** [comment]
Hi, thanks for your quick replly, here the error:

runfile('/home/mon/OGGM/delete1.py', wdir='/home/mon/OGGM')
Reloaded modules: __mp_main__
Traceback (most recent call last):

  File "<ipython-input-8-7ef4bd8f2c19>", line 1, in <module>
    runfile('/home/mon/OGGM/delete1.py', wdir='/home/mon/OGGM')

  File "/home/mon/miniconda3/envs/oggm_env/lib/python3.8/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/mon/miniconda3/envs/oggm_env/lib/python3.8/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/mon/OGGM/delete1.py", line 1, in <module>
    from oggm import salem

  File "/home/mon/miniconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/__init__.py", line 26, in <module>
    from oggm.utils import entity_task, global_task

  File "/home/mon/miniconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/utils/__init__.py", line 4, in <module>
    from oggm.utils._workflow import *

  File "/home/mon/miniconda3/envs/oggm_env/lib/python3.8/site-packages/oggm/utils/_workflow.py", line 32, in <module>
    import xarray as xr

  File "/home/mon/miniconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/__init__.py", line 3, in <module>
    from . import testing, tutorial, ufuncs

  File "/home/mon/miniconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/tutorial.py", line 14, in <module>
    from .backends.api import open_dataset as _open_dataset

  File "/home/mon/miniconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/backends/api.py", line 20, in <module>
    from ..core import backends, coding, conventions

**ImportError: cannot import name 'backends' from 'xarray.core' (/home/mon/miniconda3/envs/oggm_env/lib/python3.8/site-packages/xarray/core/__init__.py)**

**Comment by fmaussion** [comment]
OK, so it looks like it's not related to oggm or salem, but xarray. 

Can you try to reinstall xarray?

**Comment by RPellitero** [comment]
Yes, I will try and let you know, thanks

**Comment by lilianschuster** [comment]
I had a similar salem import error. In my case, I could solve it by downgrading xarray from the newest version 0.17.0 to 0.16.2 because, at least for me salem, was not compatible with xarray 0.17.0.

**Comment by fmaussion** [comment]
Ah yes ok @TimoRoth had a recent PR on salem to fix that I think: https://github.com/fmaussion/salem/pull/195

Maybe need a salem release soon

**Comment by RPellitero** [comment]
Hi, thanks **lilianschuster** and **fmaussion** because your suggestion solved the issue with salem: by downgrading xarray 0.17.0 to xarray 0.16.2
Thanks to all
